'use strict';

module.exports = [
    'add',
    'aggregate',
    'count',
    'create',
    'distinct',
    'ensureIndexes',
    'exec',
    'exec',
    'find',
    'findById',
    'findByIdAndRemove',
    'findByIdAndUpdate',
    'findOne',
    'findOneAndRemove',
    'findOneAndUpdate',
    'geoNear',
    'geoSearch',
    'index',
    'lean',
    'lean',
    'limit',
    'mapReduce',
    'plugin',
    'populate',
    'remove',
    'select',
    'set',
    'sort',
    'toObject',
    'toString',
    'update',
    'updateMany',
    'where'
];
